version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - /backend/.env

  backend:
    build:
      context: /backend/
      dockerfile: Dockerfile
    ports:
     - '8000:8000'
    restart: unless-stopped
    volumes:
      - static_value:/foodgram/static/
      - media_value:/foodgram/media/
    depends_on:
      - db
    env_file:
      - /backend/.env

  frontend:
    build:
      context: /frontend/
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/foodgram/result_build/
    depends_on:
      - backend

volumes:
  postgres_data:
  static_value:
  media_value:
  result_build: