version: '3.3'
volumes:
  postgres_data:
  static_value:
  media_value:
  result_build:
services:
  db:
    image: postgres:13.0-alpine
    environment: 
      - DB_NAME=postgres
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../backend/.env
  backend:
#    image: slavc/foodgram_backend:latest
    build:
      context: ../backend/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - ../backend/.env
  frontend:
#    image: slavc/foodgram_frontend:latest
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
    - backend
