# Generated by Django 2.2.19 on 2024-05-11 11:48

import json
from django.db import migrations


def create_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')

    with open('backend/fixtures/ingredients.json', 'r', encoding='utf-8') as intgrediets_file:
        ingrediet_objects = []
        ingrediets = json.load(intgrediets_file)

        for ingrediet in ingrediets:
            print(ingrediet['name'])
            ingrediet_objects.append(
                Ingredient(
                    name=ingrediet['name'],
                    measurement_unit=ingrediet['measurement_unit'],
                )
            )

        Ingredient.objects.bulk_create(ingrediet_objects)


def backwards(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')
    Ingredient.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0003_auto_20220320_2024'),
    ]

    operations = [
        migrations.RunPython(create_ingredients, backwards),
    ]
