# Generated by Django 2.2.19 on 2022-02-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220222_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Можете загрузить картинку', null=True, upload_to='posts/', verbose_name='картинка'),
        ),
    ]
